name = "aq2_task_dispatch"
version = "0.1.0"
license = "BSD 3-clause"
author = "gronki"
maintainer = "gronki@gmail.com"
copyright = "Copyright 2023, Dominik Gronkiewicz"

[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[executable]]
name = "console"
source-dir = "app"
main = "console.f90"

[dependencies]
yaftree = {path = "deps/yaftree"}