name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gfortran:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        gcc-ver: [14]
    name: gfortran ${{ matrix.gcc-ver }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install gfortran ${{ matrix.gcc-ver }}
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y gfortran-${{ matrix.gcc-ver }}
          echo "FPM_FC=gfortran-${{ matrix.gcc-ver }}" >> $GITHUB_ENV
          echo "FPM_CC=gcc-${{ matrix.gcc-ver }}" >> $GITHUB_ENV
          echo "FPM_CXX=g++-${{ matrix.gcc-ver }}" >> $GITHUB_ENV

      - name: Install fpm
        run: |
          curl -L https://github.com/fortran-lang/fpm/releases/download/v0.11.0/fpm-0.11.0.F90 -o fpm.F90
          $FPM_FC -O0 fpm.F90 -o fpm

      - name: Run tests (debug)
        run: ./fpm test --profile debug --flag '-ffree-line-length-none'

      - name: Run tests (release)
        run: ./fpm test --profile release --flag '-g -ffree-line-length-none'

  oneapi:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        oneapi-ver: ["2025.1", "2025.0"]
    name: oneapi ${{ matrix.oneapi-ver }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install oneapi
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg gpg-agent wget git curl
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
            | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] " \
            " https://apt.repos.intel.com/oneapi all main" \
            | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            intel-oneapi-compiler-fortran-${{ matrix.oneapi-ver }} \
            intel-oneapi-compiler-dpcpp-cpp-${{ matrix.oneapi-ver }} 
          echo "FPM_FC=ifx" >> $GITHUB_ENV
          echo "FPM_CC=icx" >> $GITHUB_ENV
          echo "FPM_CXX=icpx" >> $GITHUB_ENV

      - name: Install fpm
        run: |
          curl -L https://github.com/fortran-lang/fpm/releases/download/v0.11.0/fpm-0.11.0.F90 -o fpm.F90
          source /opt/intel/oneapi/setvars.sh
          $FPM_FC -O0 fpm.F90 -o fpm

      - name: Run tests (debug)
        run: |
          source /opt/intel/oneapi/setvars.sh
          ./fpm test --profile debug

      - name: Run tests (release)
        run: |
          source /opt/intel/oneapi/setvars.sh
          ./fpm test --profile release --flag -g

  flang:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        llvm-ver: [19, 20]

    name: flang ${{ matrix.llvm-ver }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install flang ${{ matrix.llvm-ver }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gnupg \
            lsb-release \
            ca-certificates \
            curl \
            gnupg2 \
            apt-transport-https \
            gfortran
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/llvm.asc] http://apt.llvm.org/noble/ llvm-toolchain-noble-${{ matrix.llvm-ver }} main" \
            | sudo tee /etc/apt/sources.list.d/llvm.list >/dev/null
          sudo apt-get update
          sudo apt-get install -y clang-${{ matrix.llvm-ver }} flang-${{ matrix.llvm-ver }}
          echo "FPM_FC=flang-new-${{ matrix.llvm-ver }}" >> $GITHUB_ENV
          echo "FPM_CC=clang-${{ matrix.llvm-ver }}" >> $GITHUB_ENV
          echo "FPM_CXX=clang-${{ matrix.llvm-ver }}" >> $GITHUB_ENV

      - name: Install fpm
        run: |
          curl -L https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0.F90 -o fpm.F90
          gfortran -O -g fpm.F90 -o fpm

      - name: Run tests (debug)
        run: ./fpm test --flag '-g -O0'

      - name: Run tests (release)
        run: ./fpm test --flag '-g -O3'