name: gfortran Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        gcc-ver: [11, 12, 13, 14, 15]

    name: gcc-${{ matrix.gcc-ver }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install gfortran ${{ matrix.gcc-ver }}
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y gfortran-${{ matrix.gcc-ver }}
          echo "FPM_FC=gfortran-${{ matrix.gcc-ver }}" >> $GITHUB_ENV

      - name: Install fpm
        run: |
          curl -L https://github.com/fortran-lang/fpm/releases/download/v0.11.0/fpm-0.11.0.F90 -o fpm.F90
          $FPM_FC -O0 fpm.F90 -o fpm

      - name: Run tests (debug)
        run: ./fpm test --profile debug --flag '-ffree-line-length-none'

      - name: Run tests (release)
        run: ./fpm test --flag '-O3 -funsafe-math-optimizations -g -ffree-line-length-none'