name: gfortran Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            gcc-ver: 11
          - os: ubuntu-22.04
            gcc-ver: 12
          - os: ubuntu-24.04
            gcc-ver: 13
          - os: ubuntu-24.04
            gcc-ver: 14
          - os: ubuntu-25.04
            gcc-ver: 15

    name: gcc-${{ matrix.gcc-ver }}_${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install gfortran ${{ matrix.gcc-ver }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran-${{ matrix.gcc-ver }}
          echo "FPM_FC=gfortran-${{ matrix.gcc-ver }}" >> $GITHUB_ENV

      - name: Install fpm
        run: |
          curl -L https://github.com/fortran-lang/fpm/releases/download/v0.11.0/fpm-0.11.0.F90 -o fpm.F90
          $FPM_FC -O0 fpm.F90 -o fpm

      - name: Run tests
        run: ./fpm test